<template>
  <div class="app-resource instance">
    <div class="header">
      <vxe-button status="primary" content="新建" @click="create($event)"></vxe-button>
      <vxe-button transfer>
        <template #default>更多操作</template>
        <template #dropdowns>
          <vxe-button type="text">开机</vxe-button>
          <vxe-button type="text">关机</vxe-button>
          <vxe-button type="text">重启</vxe-button>
          <vxe-button type="text">转移</vxe-button>
          <vxe-button type="text">修改密码</vxe-button>
          <vxe-button type="text">销毁</vxe-button>
        </template>
      </vxe-button>
      <!-- <vxe-button content="批量操作" transfer>
        <template #dropdowns>
          <vxe-button type="text" content="开机"></vxe-button>
          <vxe-button type="text" content="关机"></vxe-button>
          <vxe-button type="text" content="重启"></vxe-button>
          <vxe-button type="text" content="转移"></vxe-button>
          <vxe-button type="text" content="修改密码"></vxe-button>
          <vxe-button type="text" content="销毁"></vxe-button>
        </template>
      </vxe-button>-->
      <vxe-input placeholder="输入搜索关键字" suffix-icon="vxe-icon--search" clearable></vxe-input>
    </div>
    <vxe-table
      highlight-current-row
      highlight-current-column
      highlight-hover-row
      show-overflow
      :align="null"
      :data="tableData"
      :menu-config="tableMenu"
      max-height="550"
      class="table"
      style="margin-top: 12px;"
      size="small"
    >
      <vxe-table-column type="checkbox" width="40"></vxe-table-column>
      <vxe-table-column field="resourceId" title="实例ID/名称" min-width="150">
        <template slot-scope="scope">
          <span>{{scope.row.resourceId}}</span>
          <br />
          <span>{{scope.row.resourceName}}</span>
        </template>
      </vxe-table-column>
      <vxe-table-column field="resourcePoolName" title="资源池" width="100"></vxe-table-column>
      <vxe-table-column field="regionName" title="地域" width="150"></vxe-table-column>
      <vxe-table-column field="instanceState" title="状态" width="100">
        <template slot-scope="scope">
          <span :class="`status-dot ${scope.row.instanceState} `">{{scope.row.instanceStateName}}</span>
        </template>
      </vxe-table-column>
      <vxe-table-column field="ip" title="IP地址" width="120"></vxe-table-column>
      <vxe-table-column field="configure" title="系统/配置" width="120"></vxe-table-column>
      <vxe-table-column field="agentStateName" title="Agent状态" width="120"></vxe-table-column>
      <vxe-table-column field="userName" title="所属人" width="120"></vxe-table-column>
      <vxe-table-column field="corpCreateTime" title="创建时间" width="200">
        <template slot-scope="scope">
          <span>{{scope.row.corpCreateTime | formatDateTime}}</span>
        </template>
      </vxe-table-column>
    </vxe-table>
    <div class="footer">
      <vxe-pager
        :current-page.sync="page4.currentPage"
        :page-size.sync="page4.pageSize"
        :total="page4.totalResult"
        :layouts="['PrevJump', 'PrevPage', 'Number', 'NextPage', 'NextJump', 'Sizes', 'FullJump', 'Total']"
      ></vxe-pager>
    </div>
  </div>
</template>

<script lang="ts">
import {
  Component,
  Ref,
  Vue,
  Watch,
  InjectReactive
} from 'vue-property-decorator'
@Component({
  name: 'AppResourceInstance',
  components: {}
})
export default class extends Vue {
  private tableData: any = [
    {
      id: '6086527402211b1d032d32b9',
      resourceId: '8453665b-1c3a-4432-9247-1aa93102f7db',
      resourceUuid: null,
      resourceName: 'asd',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: '8b4f22a536f845769820b5777d549238',
      regionName: 'default',
      zoneId: '超分ram和CPU',
      zoneName: null,
      srn:
        'srn:tstack:instance:8b4f22a536f845769820b5777d549238:100000800000:instance/8453665b-1c3a-4432-9247-1aa93102f7db',
      corp: 'tstack',
      chargeType: null,
      chargeTypeName: null,
      accountId: 100000800000,
      accountName: null,
      accessKey: '4',
      accessKeyName: 'TStack账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '6220c51c3e564119af760cc882b34c13',
      corpProjectName: '体验项目4',
      corpCreateTime: '2021-04-26T11:52:21.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: null,
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'd276dd07-c3ce-4673-9b7e-7601a2d0dfef',
      osName: 'CentOS',
      osType: 'Linux',
      publicIPBandwidthChargeType: null,
      publicIPBandwidthChargeTypeName: null,
      publicIPBandwidth: null,
      publicIPAddresses: [],
      privateIPAddresses: ['10.0.0.26'],
      corpReleaseTime: null,
      hostName: null,
      hostId: '241b8ca78578b26ef5f527c2d1d8c6b38c2ed02f50dd63381a66ef3a',
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6086527e02211b1d032d32de',
      resourceId: 'abdebc41-c854-4d6b-97bb-7adb6ee0326e',
      resourceUuid: null,
      resourceName: 's',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: '8b4f22a536f845769820b5777d549238',
      regionName: 'default',
      zoneId: '超分ram和CPU',
      zoneName: null,
      srn:
        'srn:tstack:instance:8b4f22a536f845769820b5777d549238:100000800000:instance/abdebc41-c854-4d6b-97bb-7adb6ee0326e',
      corp: 'tstack',
      chargeType: null,
      chargeTypeName: null,
      accountId: 100000800000,
      accountName: null,
      accessKey: '4',
      accessKeyName: 'TStack账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '6220c51c3e564119af760cc882b34c13',
      corpProjectName: '体验项目4',
      corpCreateTime: '2021-04-26T11:41:18.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: null,
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'd276dd07-c3ce-4673-9b7e-7601a2d0dfef',
      osName: 'CentOS',
      osType: 'Linux',
      publicIPBandwidthChargeType: null,
      publicIPBandwidthChargeTypeName: null,
      publicIPBandwidth: null,
      publicIPAddresses: [],
      privateIPAddresses: ['10.0.0.24'],
      corpReleaseTime: null,
      hostName: null,
      hostId: '4f92dde291871ace029e7f69be78a14cad1c7d2f73c535a7f961c952',
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929302211b1d032b8e1f',
      resourceId: 'ins-q8g96iea',
      resourceUuid: 'b01c4965-4bdb-41ac-985b-2735e7613262',
      resourceName: 'tsf-app1',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-q8g96iea',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:54.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['81.71.147.73'],
      privateIPAddresses: ['172.16.16.25'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929402211b1d032b8e3c',
      resourceId: 'ins-mawxlz0m',
      resourceUuid: '99fd5d6c-3fa3-4c97-9511-567bb0706aa4',
      resourceName: 'tsf-app3',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-mawxlz0m',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:50.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['106.52.115.138'],
      privateIPAddresses: ['172.16.16.41'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929502211b1d032b8e5a',
      resourceId: 'ins-pgs8evam',
      resourceUuid: '995b4a1a-5876-4420-a1ef-afa7e0a95d34',
      resourceName: 'tsf-app2',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-pgs8evam',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:49.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['119.29.199.198'],
      privateIPAddresses: ['172.16.16.26'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5702211b1d032b173d',
      resourceId: 'ins-841k0zt6',
      resourceUuid: 'c70e150a-12fb-4a36-82fa-13be80ebc754',
      resourceName: 'front-tsf',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-841k0zt6',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:09:42.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.MEDIUM4',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 2,
      memory: 4096.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['1.14.149.173'],
      privateIPAddresses: ['172.16.16.17'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5802211b1d032b175b',
      resourceId: 'ins-nhqhndwq',
      resourceUuid: '9e2d4c7e-965d-4a98-9a48-96e5f6cfd9a3',
      resourceName: 'tsf-back2',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-nhqhndwq',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:45.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['1.14.148.183'],
      privateIPAddresses: ['172.16.16.35'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5802211b1d032b1777',
      resourceId: 'ins-dx9mvez2',
      resourceUuid: 'bf7ee929-91e7-4df5-b9e2-78cf0b46e728',
      resourceName: 'tsf-back1',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-dx9mvez2',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:40.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['134.175.32.184'],
      privateIPAddresses: ['172.16.16.48'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5902211b1d032b1794',
      resourceId: 'ins-dqchbs1a',
      resourceUuid: '3fd80d62-1a6b-449d-a7b0-be80e9c7bb2c',
      resourceName: 'tsf-back3',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-dqchbs1a',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:33.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['159.75.31.139'],
      privateIPAddresses: ['172.16.16.15'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60851e9f02211b1d032a7be9',
      resourceId: 'ins-r7hn5nv1',
      resourceUuid: 'cffa0c70-e080-4af2-84f9-d2b5dd6adc02',
      resourceName: 'zhaoyf',
      resourceType: 'instance',
      resourcePoolId: 45,
      resourcePoolName: '腾讯云-平台-zhaoyf',
      projectId: null,
      projectName: null,
      regionId: 'ap-beijing',
      regionName: '华北地区(北京)',
      zoneId: 'ap-beijing-1',
      zoneName: '北京一区',
      srn: 'srn:tcs:instance:ap-beijing:100000800000:instance/ins-r7hn5nv1',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: '8b50e5f8f7bb44bab7134c73b4217629',
      userName: 'zhaoyf',
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T15:47:34.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'SA1.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-pi0ii46r',
      osName: 'Ubuntu Server 18.04.1 LTS 64位',
      osType: 'ubuntu',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 1,
      publicIPAddresses: ['82.157.51.120'],
      privateIPAddresses: ['192.168.0.6'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6086527402211b1d032d32b9',
      resourceId: '8453665b-1c3a-4432-9247-1aa93102f7db',
      resourceUuid: null,
      resourceName: 'asd',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: '8b4f22a536f845769820b5777d549238',
      regionName: 'default',
      zoneId: '超分ram和CPU',
      zoneName: null,
      srn:
        'srn:tstack:instance:8b4f22a536f845769820b5777d549238:100000800000:instance/8453665b-1c3a-4432-9247-1aa93102f7db',
      corp: 'tstack',
      chargeType: null,
      chargeTypeName: null,
      accountId: 100000800000,
      accountName: null,
      accessKey: '4',
      accessKeyName: 'TStack账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '6220c51c3e564119af760cc882b34c13',
      corpProjectName: '体验项目4',
      corpCreateTime: '2021-04-26T11:52:21.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: null,
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'd276dd07-c3ce-4673-9b7e-7601a2d0dfef',
      osName: 'CentOS',
      osType: 'Linux',
      publicIPBandwidthChargeType: null,
      publicIPBandwidthChargeTypeName: null,
      publicIPBandwidth: null,
      publicIPAddresses: [],
      privateIPAddresses: ['10.0.0.26'],
      corpReleaseTime: null,
      hostName: null,
      hostId: '241b8ca78578b26ef5f527c2d1d8c6b38c2ed02f50dd63381a66ef3a',
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6086527e02211b1d032d32de',
      resourceId: 'abdebc41-c854-4d6b-97bb-7adb6ee0326e',
      resourceUuid: null,
      resourceName: 's',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: '8b4f22a536f845769820b5777d549238',
      regionName: 'default',
      zoneId: '超分ram和CPU',
      zoneName: null,
      srn:
        'srn:tstack:instance:8b4f22a536f845769820b5777d549238:100000800000:instance/abdebc41-c854-4d6b-97bb-7adb6ee0326e',
      corp: 'tstack',
      chargeType: null,
      chargeTypeName: null,
      accountId: 100000800000,
      accountName: null,
      accessKey: '4',
      accessKeyName: 'TStack账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '6220c51c3e564119af760cc882b34c13',
      corpProjectName: '体验项目4',
      corpCreateTime: '2021-04-26T11:41:18.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: null,
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'd276dd07-c3ce-4673-9b7e-7601a2d0dfef',
      osName: 'CentOS',
      osType: 'Linux',
      publicIPBandwidthChargeType: null,
      publicIPBandwidthChargeTypeName: null,
      publicIPBandwidth: null,
      publicIPAddresses: [],
      privateIPAddresses: ['10.0.0.24'],
      corpReleaseTime: null,
      hostName: null,
      hostId: '4f92dde291871ace029e7f69be78a14cad1c7d2f73c535a7f961c952',
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929302211b1d032b8e1f',
      resourceId: 'ins-q8g96iea',
      resourceUuid: 'b01c4965-4bdb-41ac-985b-2735e7613262',
      resourceName: 'tsf-app1',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-q8g96iea',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:54.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['81.71.147.73'],
      privateIPAddresses: ['172.16.16.25'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929402211b1d032b8e3c',
      resourceId: 'ins-mawxlz0m',
      resourceUuid: '99fd5d6c-3fa3-4c97-9511-567bb0706aa4',
      resourceName: 'tsf-app3',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-mawxlz0m',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:50.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['106.52.115.138'],
      privateIPAddresses: ['172.16.16.41'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929502211b1d032b8e5a',
      resourceId: 'ins-pgs8evam',
      resourceUuid: '995b4a1a-5876-4420-a1ef-afa7e0a95d34',
      resourceName: 'tsf-app2',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-pgs8evam',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:49.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['119.29.199.198'],
      privateIPAddresses: ['172.16.16.26'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5702211b1d032b173d',
      resourceId: 'ins-841k0zt6',
      resourceUuid: 'c70e150a-12fb-4a36-82fa-13be80ebc754',
      resourceName: 'front-tsf',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-841k0zt6',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:09:42.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.MEDIUM4',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 2,
      memory: 4096.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['1.14.149.173'],
      privateIPAddresses: ['172.16.16.17'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5802211b1d032b175b',
      resourceId: 'ins-nhqhndwq',
      resourceUuid: '9e2d4c7e-965d-4a98-9a48-96e5f6cfd9a3',
      resourceName: 'tsf-back2',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-nhqhndwq',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:45.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['1.14.148.183'],
      privateIPAddresses: ['172.16.16.35'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5802211b1d032b1777',
      resourceId: 'ins-dx9mvez2',
      resourceUuid: 'bf7ee929-91e7-4df5-b9e2-78cf0b46e728',
      resourceName: 'tsf-back1',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-dx9mvez2',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:40.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['134.175.32.184'],
      privateIPAddresses: ['172.16.16.48'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5902211b1d032b1794',
      resourceId: 'ins-dqchbs1a',
      resourceUuid: '3fd80d62-1a6b-449d-a7b0-be80e9c7bb2c',
      resourceName: 'tsf-back3',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-dqchbs1a',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:33.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['159.75.31.139'],
      privateIPAddresses: ['172.16.16.15'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60851e9f02211b1d032a7be9',
      resourceId: 'ins-r7hn5nv1',
      resourceUuid: 'cffa0c70-e080-4af2-84f9-d2b5dd6adc02',
      resourceName: 'zhaoyf',
      resourceType: 'instance',
      resourcePoolId: 45,
      resourcePoolName: '腾讯云-平台-zhaoyf',
      projectId: null,
      projectName: null,
      regionId: 'ap-beijing',
      regionName: '华北地区(北京)',
      zoneId: 'ap-beijing-1',
      zoneName: '北京一区',
      srn: 'srn:tcs:instance:ap-beijing:100000800000:instance/ins-r7hn5nv1',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: '8b50e5f8f7bb44bab7134c73b4217629',
      userName: 'zhaoyf',
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T15:47:34.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'SA1.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-pi0ii46r',
      osName: 'Ubuntu Server 18.04.1 LTS 64位',
      osType: 'ubuntu',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 1,
      publicIPAddresses: ['82.157.51.120'],
      privateIPAddresses: ['192.168.0.6'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6086527402211b1d032d32b9',
      resourceId: '8453665b-1c3a-4432-9247-1aa93102f7db',
      resourceUuid: null,
      resourceName: 'asd',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: '8b4f22a536f845769820b5777d549238',
      regionName: 'default',
      zoneId: '超分ram和CPU',
      zoneName: null,
      srn:
        'srn:tstack:instance:8b4f22a536f845769820b5777d549238:100000800000:instance/8453665b-1c3a-4432-9247-1aa93102f7db',
      corp: 'tstack',
      chargeType: null,
      chargeTypeName: null,
      accountId: 100000800000,
      accountName: null,
      accessKey: '4',
      accessKeyName: 'TStack账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '6220c51c3e564119af760cc882b34c13',
      corpProjectName: '体验项目4',
      corpCreateTime: '2021-04-26T11:52:21.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: null,
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'd276dd07-c3ce-4673-9b7e-7601a2d0dfef',
      osName: 'CentOS',
      osType: 'Linux',
      publicIPBandwidthChargeType: null,
      publicIPBandwidthChargeTypeName: null,
      publicIPBandwidth: null,
      publicIPAddresses: [],
      privateIPAddresses: ['10.0.0.26'],
      corpReleaseTime: null,
      hostName: null,
      hostId: '241b8ca78578b26ef5f527c2d1d8c6b38c2ed02f50dd63381a66ef3a',
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6086527e02211b1d032d32de',
      resourceId: 'abdebc41-c854-4d6b-97bb-7adb6ee0326e',
      resourceUuid: null,
      resourceName: 's',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: '8b4f22a536f845769820b5777d549238',
      regionName: 'default',
      zoneId: '超分ram和CPU',
      zoneName: null,
      srn:
        'srn:tstack:instance:8b4f22a536f845769820b5777d549238:100000800000:instance/abdebc41-c854-4d6b-97bb-7adb6ee0326e',
      corp: 'tstack',
      chargeType: null,
      chargeTypeName: null,
      accountId: 100000800000,
      accountName: null,
      accessKey: '4',
      accessKeyName: 'TStack账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '6220c51c3e564119af760cc882b34c13',
      corpProjectName: '体验项目4',
      corpCreateTime: '2021-04-26T11:41:18.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: null,
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'd276dd07-c3ce-4673-9b7e-7601a2d0dfef',
      osName: 'CentOS',
      osType: 'Linux',
      publicIPBandwidthChargeType: null,
      publicIPBandwidthChargeTypeName: null,
      publicIPBandwidth: null,
      publicIPAddresses: [],
      privateIPAddresses: ['10.0.0.24'],
      corpReleaseTime: null,
      hostName: null,
      hostId: '4f92dde291871ace029e7f69be78a14cad1c7d2f73c535a7f961c952',
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929302211b1d032b8e1f',
      resourceId: 'ins-q8g96iea',
      resourceUuid: 'b01c4965-4bdb-41ac-985b-2735e7613262',
      resourceName: 'tsf-app1',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-q8g96iea',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:54.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['81.71.147.73'],
      privateIPAddresses: ['172.16.16.25'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929402211b1d032b8e3c',
      resourceId: 'ins-mawxlz0m',
      resourceUuid: '99fd5d6c-3fa3-4c97-9511-567bb0706aa4',
      resourceName: 'tsf-app3',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-mawxlz0m',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:50.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['106.52.115.138'],
      privateIPAddresses: ['172.16.16.41'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '6085929502211b1d032b8e5a',
      resourceId: 'ins-pgs8evam',
      resourceUuid: '995b4a1a-5876-4420-a1ef-afa7e0a95d34',
      resourceName: 'tsf-app2',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-pgs8evam',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T22:31:49.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['119.29.199.198'],
      privateIPAddresses: ['172.16.16.26'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5702211b1d032b173d',
      resourceId: 'ins-841k0zt6',
      resourceUuid: 'c70e150a-12fb-4a36-82fa-13be80ebc754',
      resourceName: 'front-tsf',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-841k0zt6',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:09:42.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.MEDIUM4',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 2,
      memory: 4096.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['1.14.149.173'],
      privateIPAddresses: ['172.16.16.17'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5802211b1d032b175b',
      resourceId: 'ins-nhqhndwq',
      resourceUuid: '9e2d4c7e-965d-4a98-9a48-96e5f6cfd9a3',
      resourceName: 'tsf-back2',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-nhqhndwq',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:45.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['1.14.148.183'],
      privateIPAddresses: ['172.16.16.35'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5802211b1d032b1777',
      resourceId: 'ins-dx9mvez2',
      resourceUuid: 'bf7ee929-91e7-4df5-b9e2-78cf0b46e728',
      resourceName: 'tsf-back1',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-dx9mvez2',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:40.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['134.175.32.184'],
      privateIPAddresses: ['172.16.16.48'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60855a5902211b1d032b1794',
      resourceId: 'ins-dqchbs1a',
      resourceUuid: '3fd80d62-1a6b-449d-a7b0-be80e9c7bb2c',
      resourceName: 'tsf-back3',
      resourceType: 'instance',
      resourcePoolId: null,
      resourcePoolName: null,
      projectId: null,
      projectName: null,
      regionId: 'ap-guangzhou',
      regionName: '华南地区(广州)',
      zoneId: 'ap-guangzhou-3',
      zoneName: '广州三区',
      srn: 'srn:tcs:instance:ap-guangzhou:100000800000:instance/ins-dqchbs1a',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: null,
      userName: null,
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T18:04:33.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'S5.4XLARGE32',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 16,
      memory: 32768.0,
      imageId: 'img-oikl1tzv',
      osName: 'CentOS 7.5 64位',
      osType: 'centos',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 100,
      publicIPAddresses: ['159.75.31.139'],
      privateIPAddresses: ['172.16.16.15'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    },
    {
      id: '60851e9f02211b1d032a7be9',
      resourceId: 'ins-r7hn5nv1',
      resourceUuid: 'cffa0c70-e080-4af2-84f9-d2b5dd6adc02',
      resourceName: 'zhaoyf',
      resourceType: 'instance',
      resourcePoolId: 45,
      resourcePoolName: '腾讯云-平台-zhaoyf',
      projectId: null,
      projectName: null,
      regionId: 'ap-beijing',
      regionName: '华北地区(北京)',
      zoneId: 'ap-beijing-1',
      zoneName: '北京一区',
      srn: 'srn:tcs:instance:ap-beijing:100000800000:instance/ins-r7hn5nv1',
      corp: 'tcs',
      chargeType: 'postPaid',
      chargeTypeName: '按量付费',
      accountId: 100000800000,
      accountName: null,
      accessKey: 'AKIDRe7LK3ljiSvUsdbVYLuu2g5w4zf7oI0F',
      accessKeyName: '腾讯云账号',
      accessKeyId: null,
      userId: '8b50e5f8f7bb44bab7134c73b4217629',
      userName: 'zhaoyf',
      organizationId: null,
      organizationName: null,
      recyclePolicy: null,
      recycleTime: null,
      recycleRemainDay: null,
      expired: null,
      corpProjectId: '0',
      corpProjectName: null,
      corpCreateTime: '2021-04-25T15:47:34.000+0800',
      corpExpiredTime: null,
      projectDomainName: null,
      instanceTypeName: null,
      instanceType: 'SA1.SMALL2',
      instanceState: 'running',
      instanceStateName: '运行中',
      cpu: 1,
      memory: 2048.0,
      imageId: 'img-pi0ii46r',
      osName: 'Ubuntu Server 18.04.1 LTS 64位',
      osType: 'ubuntu',
      publicIPBandwidthChargeType: 'traffic',
      publicIPBandwidthChargeTypeName: '按量计费',
      publicIPBandwidth: 1,
      publicIPAddresses: ['82.157.51.120'],
      privateIPAddresses: ['192.168.0.6'],
      corpReleaseTime: null,
      hostName: null,
      hostId: null,
      agentState: null,
      agentStateName: null,
      portId: null,
      azureField: null,
      openStackField: null,
      tstackField: null,
      vmwareField: null,
      eipPublicIPType: false
    }
  ]

  private tableMenu = {
    header: {
      options: [
        [
          {
            code: 'exportAll',
            name: '导出所有.csv',
            prefixIcon: 'fa fa-download',
            visible: true,
            disabled: false
          }
        ]
      ]
    },
    body: {
      options: [
        [
          {
            code: 'copy',
            name: '复制内容',
            prefixIcon: 'fa fa-copy',
            visible: true,
            disabled: false
          },
          { code: 'clear', name: '清除内容', visible: true, disabled: false },
          { code: 'reload', name: '刷新表格', visible: true, disabled: false }
        ],
        [
          {
            code: 'myPrint',
            name: '打印',
            prefixIcon: 'fa fa-print',
            visible: true,
            disabled: false
          },
          {
            code: 'myExport',
            name: '导出.csv',
            prefixIcon: 'fa fa-download',
            visible: true,
            disabled: false
          }
        ]
      ]
    },
    footer: {
      options: [
        [
          {
            code: 'exportAll',
            name: '导出所有.csv',
            prefixIcon: 'fa fa-download',
            visible: true,
            disabled: false
          }
        ]
      ]
    }
  }

  private page4 = {
    currentPage: 1,
    pageSize: 10,
    totalResult: 300
  }

  @InjectReactive()
  public window

  private create () {
    this.$XWindow.create(
      {
        title: '创建云服务器'
      },
      this.window
    )
  }
}
</script>

<style lang="less" scoped>
@theme-dark-color: #262a36;
@nav-header-height: 50px;

@white: #fff;
@black: #000;
@light-grey: #e8e8e8;
@theme-blue: #2061ff;
@bg-grey-color: #f9fafc;
@light-gray: #ccc;
@font-gray: #999;
@basic-black: #4b556a;
@font-red-tip: #f54743;
@basic-color: #333;
@success-color: #35ba65;
@error-color: #f04621;
@refresh-color: #398fff;
@light-black: #666;
@danger: #f54743;
@success: #2fc25b;
@warning: #fad337;
@tip: #ff9900;
@bg-gray-color: #f9f9f9;
@success-bg: #0abf5b;
@warning-bg: #ed711f;
@error-bg: #c9191e;
@border-bottom-color: #30475e;

.app-resource.instance {
  height: 100%;
  padding: 12px;
  position: relative;
  .header {
    height: 30px;
  }
  // .table {
  //   height: calc(~'100% - 66px');
  // }
  .footer {
    position: absolute;
    width: calc(~'100% - 24px');
    height: 40px;
    bottom: 0;
  }
}
.status-dot {
  display: inline-block;
  padding: 2px 4px;
  border-radius: 4px;
  font-size: 12px;
  position: relative;
  &.success,
  &.enabled,
  &.running,
  &.poweredOn,
  &.connected,
  &.bind,
  &.available,
  &.attached,
  &.status--1,
  &.in_use,
  &.active {
    color: @success-color;
    &::before {
      background-color: @success-color;
    }
  }
  &.fail,
  &.disabled,
  &.poweredOff,
  &.stopped,
  &.disconnected,
  &.error,
  &.unbind,
  &.unattached,
  &.down,
  &.suspended,
  &.status--0,
  &.isolated,
  &.shutoff {
    color: @error-color;
    &::before {
      background-color: @error-color;
    }
  }

  &.creating,
  &.in-use,
  &.queued,
  &.stopping,
  &.rebooting,
  &.transing,
  &.rebuild,
  &.hardReboot,
  &.binding,
  &.unbinding,
  &.offlining,
  &.isolating,
  &.pending {
    color: @tip;
    &::before {
      background-color: @tip;
    }
  }
  &::before {
    content: '';
    position: absolute;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    left: -10px;
    top: 0;
    bottom: 0;
    margin: auto;
    z-index: 1;
  }
}

/* 设置动画前颜色 */
.status-dot-flicker::after {
  background-color: @success-color;
}

/* 设置动画后颜色 */
.status-dot-flicker::before {
  background-color: hsl(@success-color, 20%);
}

/* 设置动画 */
.status-dot-flicker::before,
.status-dot-flicker::after {
  content: '';
  position: absolute;
  z-index: 0;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  left: -12px;
  top: 0;
  bottom: 0;
  margin: auto;
  /* CSS3 animation 属性 网址 */
  /* https://www.w3school.com.cn/cssref/pr_animation.asp */
  animation: status-dot 2s ease-out 0s infinite;
}

@keyframes status-dot {
  0% {
    transform: scale(0.5);
    opacity: 1;
  }

  30% {
    opacity: 1;
  }

  100% {
    transform: scale(1.4);
    opacity: 0;
  }
}
</style>
